services:
  print-marks-app:
    container_name: print-marks-app
    build:
      context: .
      args:
        VITE_EMAIL_SERVICE_ID: ${VITE_EMAIL_SERVICE_ID}
        VITE_EMAIL_TEMPLATE_ID: ${VITE_EMAIL_TEMPLATE_ID}
        VITE_EMAIL_PUBLIC_KEY: ${VITE_EMAIL_PUBLIC_KEY}
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
networks:
  app-network:
    name: app-network
