version: '3.8'

services:
  print-marks-app:
    build: .
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
networks:
  app-network:
    name: app-network
